# Generated by Django 4.0.1 on 2022-02-07 23:15

import books.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('publication_year', models.PositiveSmallIntegerField(null=True, validators=[books.validators.year_validator])),
                ('ISBN', models.CharField(max_length=13, null=True, unique=True, validators=[books.validators.isbn_validator])),
                ('no_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(max_length=300, null=True)),
                ('authors', models.ManyToManyField(to='books.Author')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language')),
            ],
        ),
    ]
