services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./app/envs/.env.db.dev
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - 8000:8000
    env_file:
      - ./app/envs/.env.dev
    depends_on:
      - db
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
  media_volume:
